import { useState } from 'react';
import { Plus, Loader2, AlertCircle, Sparkles } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useApp } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import { Modal } from './Modal';

function FieldError({ show, children }: { show: boolean; children: React.ReactNode }) {
  if (!show) return null;
  return (
    <div className="flex items-center gap-1 mt-1 text-xs text-red-500">
      <AlertCircle className="w-3 h-3 shrink-0" />
      {children}
    </div>
  );
}

function inputErrorClass(error: string | undefined, touched: boolean): string {
  if (touched && error) return 'input border-red-300 focus:ring-red-500/10 focus:border-red-400';
  return 'input';
}

export function QuickCreateArticleModal({ open, onClose, onCreated, initialName }: {
  open: boolean;
  onClose: () => void;
  onCreated: (article: any) => void;
  initialName?: string;
}) {
  const { tenant, currentSite } = useApp();
  const { success, error } = useToast();
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState(initialName || '');
  const [salePrice, setSalePrice] = useState('');
  const [purchasePrice, setPurchasePrice] = useState('');
  const [ref, setRef] = useState('');
  const [refAutoGenerated, setRefAutoGenerated] = useState(false);
  const [stockInit, setStockInit] = useState('');
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validateField = (field: string, value: string): string | undefined => {
    if (field === 'name' && !value.trim()) return 'La désignation est obligatoire';
    if (field === 'salePrice' && (!value || isNaN(Number(value)) || Number(value) < 0)) return 'Prix de vente invalide';
    if (field === 'purchasePrice' && value && (isNaN(Number(value)) || Number(value) < 0)) return 'Prix d\'achat invalide';
    return undefined;
  };

  const setField = (field: 'name' | 'salePrice' | 'purchasePrice' | 'ref' | 'stockInit', value: string) => {
    if (field === 'name') setName(value);
    if (field === 'salePrice') setSalePrice(value);
    if (field === 'purchasePrice') setPurchasePrice(value);
    if (field === 'ref') { setRef(value); setRefAutoGenerated(false); }
    if (field === 'stockInit') setStockInit(value);
    const err = validateField(field, value);
    setErrors(prev => ({ ...prev, [field]: err || '' }));
  };

  const blurField = (field: string) => {
    setTouched(prev => ({ ...prev, [field]: true }));
    // Smart default: auto-generate ref from name if ref is empty
    if (field === 'ref' && !ref.trim() && name.trim()) {
      const generated = `ART-${name.trim().substring(0, 3).toUpperCase()}-${Date.now().toString(36).slice(-4).toUpperCase()}`;
      setRef(generated);
      setRefAutoGenerated(true);
    }
  };

  const validateAll = (): boolean => {
    const fields = ['name', 'salePrice', 'purchasePrice'];
    const errs: Record<string, string> = {};
    let ok = true;
    for (const f of fields) {
      const val = f === 'name' ? name : f === 'salePrice' ? salePrice : purchasePrice;
      const e = validateField(f, val);
      if (e) { errs[f] = e; ok = false; }
    }
    setErrors(errs);
    setTouched(Object.fromEntries(fields.map(f => [f, true])));
    return ok;
  };

  const handleSave = async () => {
    if (!validateAll()) { error('Veuillez corriger les champs en rouge'); return; }
    if (!tenant) return;
    setSaving(true);
    const finalRef = ref.trim() || `ART-${name.trim().substring(0, 3).toUpperCase()}-${Date.now().toString(36).slice(-4).toUpperCase()}`;
    const { data, error: err } = await supabase.from('articles').insert({
      tenant_id: tenant.id,
      site_id: currentSite?.id || null,
      name: name.trim(),
      sale_price: Number(salePrice),
      purchase_price: Number(purchasePrice) || 0,
      internal_ref: finalRef,
      is_active: true,
      stock_min: 0,
      stock_max: 0,
      vat_rate: 0,
      min_price: 0,
      wholesale_price: 0,
      description: '',
      brand: '',
      oem_ref: '',
      supplier_ref: '',
      barcode: '',
      condition: 'new',
      unit: 'pce',
      location: '',
      image_url: '',
    }).select().single();
    if (err) { setSaving(false); error(err.message); return; }

    if (data && stockInit && Number(stockInit) > 0 && currentSite) {
      await supabase.rpc('adjust_stock', {
        p_article_id: data.id,
        p_site_id: currentSite.id,
        p_quantity: Number(stockInit),
        p_movement_type: 'initial',
        p_note: 'Stock initial',
      });
    }

    setSaving(false);
    success('Article créé');
    onCreated(data);
    setName(''); setSalePrice(''); setPurchasePrice(''); setRef(''); setStockInit(''); setRefAutoGenerated(false);
    setErrors({}); setTouched({});
    onClose();
  };

  return (
    <Modal open={open} onClose={onClose} title="Créer un article" size="sm" layer="top"
      footer={
        <button onClick={handleSave} disabled={saving}
          className="btn-primary text-sm px-5 py-2.5 disabled:opacity-50">
          {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Enregistrer'}
        </button>
      }>
      <div className="space-y-3">
        <div>
          <label className="label">Désignation <span className="text-red-500">*</span></label>
          <input
            value={name}
            onChange={e => setField('name', e.target.value)}
            onBlur={() => blurField('name')}
            className={inputErrorClass(errors.name, touched.name)}
            placeholder="Nom de l'article"
            autoFocus
          />
          <FieldError show={!!touched.name && !!errors.name}>{errors.name}</FieldError>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label">Prix de vente <span className="text-red-500">*</span></label>
            <input
              type="number"
              value={salePrice}
              onChange={e => setField('salePrice', e.target.value)}
              onBlur={() => blurField('salePrice')}
              className={inputErrorClass(errors.salePrice, touched.salePrice)}
              placeholder="0"
            />
            <FieldError show={!!touched.salePrice && !!errors.salePrice}>{errors.salePrice}</FieldError>
          </div>
          <div>
            <label className="label">Prix d'achat</label>
            <input
              type="number"
              value={purchasePrice}
              onChange={e => setField('purchasePrice', e.target.value)}
              onBlur={() => blurField('purchasePrice')}
              className={inputErrorClass(errors.purchasePrice, touched.purchasePrice)}
              placeholder="0"
            />
            <FieldError show={!!touched.purchasePrice && !!errors.purchasePrice}>{errors.purchasePrice}</FieldError>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label">Référence interne</label>
            <div className="relative">
              <input
                value={ref}
                onChange={e => setField('ref', e.target.value)}
                onBlur={() => blurField('ref')}
                className={`input ${refAutoGenerated ? 'pr-9' : ''}`}
                placeholder="Auto-générée"
              />
              {refAutoGenerated && (
                <Sparkles className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-amber-400 pointer-events-none" />
              )}
            </div>
            <p className="mt-1 text-xs text-neutral-500">{refAutoGenerated ? 'Auto-générée — modifiable' : 'Laissez vide pour auto-générer'}</p>
          </div>
          <div>
            <label className="label">Stock initial</label>
            <input type="number" value={stockInit} onChange={e => setField('stockInit', e.target.value)} className="input" placeholder="0" min="0" />
          </div>
        </div>
      </div>
    </Modal>
  );
}

export function QuickCreateCustomerModal({ open, onClose, onCreated, initialName }: {
  open: boolean;
  onClose: () => void;
  onCreated: (customer: any) => void;
  initialName?: string;
}) {
  const { tenant, currentSite } = useApp();
  const { success, error } = useToast();
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState(initialName || '');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [nameTouched, setNameTouched] = useState(false);
  const [nameError, setNameError] = useState('');

  const handleSave = async () => {
    if (!name.trim()) { setNameError('Le nom est obligatoire'); setNameTouched(true); return; }
    if (!tenant) return;
    setSaving(true);
    const { data, error: err } = await supabase.from('customers').insert({
      tenant_id: tenant.id,
      site_id: currentSite?.id || null,
      name: name.trim(),
      phone: phone.trim(),
      address: address.trim(),
      email: '',
      customer_type: 'individual',
      balance: 0,
      credit_limit: 0,
      is_active: true,
    }).select().single();
    setSaving(false);
    if (err) { error(err.message); return; }
    success('Client créé');
    onCreated(data);
    setName(''); setPhone(''); setAddress(''); setNameError(''); setNameTouched(false);
    onClose();
  };

  return (
    <Modal open={open} onClose={onClose} title="Créer un client" size="sm" layer="top"
      footer={
        <button onClick={handleSave} disabled={saving}
          className="btn-primary text-sm px-5 py-2.5 disabled:opacity-50">
          {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Enregistrer'}
        </button>
      }>
      <div className="space-y-3">
        <div>
          <label className="label">Nom <span className="text-red-500">*</span></label>
          <input
            value={name}
            onChange={e => { setName(e.target.value); if (nameTouched) setNameError(e.target.value.trim() ? '' : 'Le nom est obligatoire'); }}
            onBlur={() => { setNameTouched(true); setNameError(name.trim() ? '' : 'Le nom est obligatoire'); }}
            className={inputErrorClass(nameError, nameTouched)}
            placeholder="Nom du client"
            autoFocus
          />
          <FieldError show={nameTouched && !!nameError}>{nameError}</FieldError>
        </div>
        <div>
          <label className="label">Téléphone</label>
          <input value={phone} onChange={e => setPhone(e.target.value)} className="input" placeholder="77 000 00 00" />
        </div>
        <div>
          <label className="label">Adresse</label>
          <input value={address} onChange={e => setAddress(e.target.value)} className="input" placeholder="Adresse" />
        </div>
      </div>
    </Modal>
  );
}

export function QuickCreateButton({ label, onClick }: { label: string; onClick: () => void }) {
  return (
    <button
      type="button"
      onMouseDown={e => { e.preventDefault(); e.stopPropagation(); onClick(); }}
      className="w-full flex items-center gap-2 px-3 py-2.5 text-xs font-semibold text-teal-700 bg-teal-50 hover:bg-teal-100 transition-colors border-t border-slate-100"
    >
      <Plus className="w-3.5 h-3.5" />
      {label}
    </button>
  );
}
